name: microwasteanimals
include:
- /var/lib/arduino-app-cli/assets/0.9.0/compose/arduino/video_object_detection/brick_compose.yaml
services:
  main:
    image: ghcr.io/arduino/app-bricks/python-apps-base:0.9.0
    depends_on:
      ei-video-obj-detection-runner:
        condition: service_healthy
    volumes:
    - type: bind
      source: /home/arduino/ArduinoApps/microwasteanimals
      target: /app
    - type: bind
      source: /var/run/arduino-router.sock
      target: /var/run/arduino-router.sock
    - type: bind
      source: /dev/v4l
      target: /dev/v4l
    - type: bind
      source: /dev/snd/by-id
      target: /dev/snd/by-id
    - type: bind
      source: /sys/class/leds/blue:user
      target: /sys/class/leds/blue:user
    - type: bind
      source: /sys/class/leds/green:user
      target: /sys/class/leds/green:user
    - type: bind
      source: /sys/class/leds/red:user
      target: /sys/class/leds/red:user
    - type: bind
      source: /sys/class/leds/blue:bt
      target: /sys/class/leds/blue:bt
    - type: bind
      source: /sys/class/leds/green:wlan
      target: /sys/class/leds/green:wlan
    - type: bind
      source: /sys/class/leds/red:panic
      target: /sys/class/leds/red:panic
    devices:
    - /dev/video0
    - /dev/video1
    - /dev/video2
    - /dev/video3
    - /dev/snd
    - /dev/dri
    ports:
    - 7000:7000
    user: 1000:1000
    group_add:
    - 44
    - 29
    - 991
    - 20
    - 1001
    entrypoint: /run.sh
    extra_hosts:
    - msgpack-rpc-router:host-gateway
    labels:
      cc.arduino.app: "true"
      cc.arduino.app.main: "true"
      cc.arduino.app.path: /home/arduino/ArduinoApps/microwasteanimals
    environment:
      APP_HOME: /home/arduino/ArduinoApps/microwasteanimals
      BIND_ADDRESS: 0.0.0.0
      CUSTOM_MODEL_PATH: /home/arduino/.arduino-bricks/models/custom-ei/ei-model-991365-1
      EI_OBJ_DETECTION_MODEL: /home/arduino/.arduino-bricks/models/custom-ei/ei-model-991365-1/model.eim
      EI_V_OBJ_DETECTION_MODEL: /home/arduino/.arduino-bricks/models/custom-ei/ei-model-991365-1/model.eim
      HOST_IP: 10.63.0.88
      VIDEO_DEVICE: /dev/video0
    logging:
      driver: json-file
      options:
        max-file: "2"
        max-size: 5m
