services:
  ei-video-obj-detection-runner:
    user: 1000:1000
    devices:
    - /dev/video0
    - /dev/video1
    - /dev/video2
    - /dev/video3
    - /dev/snd
    - /dev/dri
    group_add:
    - 44
    - 29
    - 991
    - 20
    - 1001
    labels:
      cc.arduino.app: "true"
      cc.arduino.app.path: /home/arduino/ArduinoApps/microwasteanimals
    environment:
      APP_HOME: /home/arduino/ArduinoApps/microwasteanimals
      BIND_ADDRESS: 0.0.0.0
      CUSTOM_MODEL_PATH: /home/arduino/.arduino-bricks/models/custom-ei/ei-model-991365-1
      EI_OBJ_DETECTION_MODEL: /home/arduino/.arduino-bricks/models/custom-ei/ei-model-991365-1/model.eim
      EI_V_OBJ_DETECTION_MODEL: /home/arduino/.arduino-bricks/models/custom-ei/ei-model-991365-1/model.eim
      HOST_IP: 10.63.0.88
      VIDEO_DEVICE: /dev/video0
